version: '3.3'

services:
  nginx:
    image: nginx:1.19-alpine
    ports:
      - "8536:8536"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - lemmy
      - pictrs
      - iframely
    restart: "always"

  lemmy:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    restart: always
    environment:
      - RUST_LOG=debug
    volumes:
      - ../lemmy.hjson:/config/config.hjson
    depends_on: 
      - postgres
      - iframely

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  pictrs:
    image: asonix/pictrs:amd64-v0.1.0-r9
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always

  iframely:
    image: dogbin/iframely:latest
    volumes:
      - ../iframely.config.local.js:/iframely/config.local.js:ro
    restart: always
