version: '2.4'

services:
  lemmy_db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: rrr
      POSTGRES_PASSWORD: rrr
      POSTGRES_DB: rrr
    volumes:
      - lemmy_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rrr"]
      interval: 5s
      timeout: 5s
      retries: 20
  lemmy:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8536:8536"
    environment:
      LEMMY_FRONT_END_DIR: /app/dist
      DATABASE_URL: postgres://rrr:rrr@lemmy_db:5432/rrr
      JWT_SECRET: changeme
      HOSTNAME: rrr
    restart: always
    depends_on: 
      lemmy_db: 
        condition: service_healthy 
volumes:
  lemmy_db:
