---
  kind: pipeline
  type: docker
  name: deploy

  trigger:
    branch:
      - dev
      - prod
    event:
      exclude:
      - pull_request
  
  globals: 
    - &docker_settings
      username:
        from_secret: CHAPO_REGISTRY_USER
      password:
        from_secret: CHAPO_REGISTRY_TOKEN
      registry:
        from_secret: CHAPO_REGISTRY_URL
      repo:
        from_secret: CHAPO_REGISTRY_URL_REPO

  clone:
    skip_verify: true
  
  steps:
  - name: prepare
    image: busybox
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
    volumes:
      - name: cache
        path: /cache

  - name: docker
    image: plugins/docker
    settings:
      create_repository: true
      use_cache: true
      dockerfile: docker/prod/Dockerfile
      <<: *docker_settings
      tags:
        - ${DRONE_BRANCH}-latest
        - ${DRONE_COMMIT_SHA:0:8}
    volumes:
      - name: docker
        path: /var/lib/docker

  - name: notify
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      message: >
        {{#success build.status}}
        ✅  Build #{{build.number}} of `{{repo.name}}` succeeded.
        📝 Commit by {{commit.author}} on `{{commit.branch}}`:
        ``` {{commit.message}} ```
        🌐 {{ build.link }}
        ✅ duration: {{duration build.started build.finished}}
        ✅ started: {{datetime build.started "2006/01/02 15:04" "UTC"}}
        ✅ finished: {{datetime build.finished "2006/01/02 15:04" "UTC"}}
        {{else}}
        ❌  Build #{{build.number}} of `{{repo.name}}` failed.
        📝 Commit by {{commit.author}} on `{{commit.branch}}`:
        ``` {{commit.message}} ```
        🌐 {{ build.link }}
        ✅ duration: {{duration build.started build.finished}}
        ✅ started: {{datetime build.started "2006/01/02 15:04" "UTC"}}
        ✅ finished: {{datetime build.finished "2006/01/02 15:04" "UTC"}}
        {{/success}}
    when:
      status:
      - success
      - failure

  volumes:
    - name: cache
      host:
        path: /var/cache
    - name: docker
      host:
        path: /var/cache/${DRONE_REPO}/docker



---
  kind: pipeline
  type: docker
  name: test

  trigger:
    branch:
      - main

  globals: 
    - &docker_settings
      username:
        from_secret: CHAPO_REGISTRY_USER
      password:
        from_secret: CHAPO_REGISTRY_TOKEN
      registry:
        from_secret: CHAPO_REGISTRY_URL
      repo:
        from_secret: CHAPO_REGISTRY_URL_REPO

  clone:
    skip_verify: true

  steps:
  - name: prepare
    image: busybox
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
    volumes:
      - name: cache
        path: /cache

  - name: build
    image: plugins/docker
    settings:
      create_repository: true
      use_cache: true
      dockerfile: docker/prod/Dockerfile
      dry_run: true
      <<: *docker_settings
      tags:
        - ${DRONE_BRANCH}-latest
        - ${DRONE_COMMIT_SHA:0:8}
    when:
      event: [ push, pull_request ]
    volumes:
      - name: docker
        path: /var/lib/docker


  - name: publish
    image: plugins/docker
    settings:
      create_repository: true
      use_cache: true
      dockerfile: docker/prod/Dockerfile
      <<: *docker_settings
      tags:
        - ${DRONE_BRANCH}-latest
        - ${DRONE_COMMIT_SHA:0:8}
    when:
      event: [ push, pull_request ]

  - name: notify
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      message: >
        {{#success build.status}}
        ✅  Build #{{build.number}} of `{{repo.name}}` succeeded.
        📝 Commit by {{commit.author}} on `{{commit.branch}}`:
        ``` {{commit.message}} ```
        🌐 {{ build.link }}
        ✅ duration: {{duration build.started build.finished}}
        ✅ started: {{datetime build.started "2006/01/02 15:04" "UTC"}}
        ✅ finished: {{datetime build.finished "2006/01/02 15:04" "UTC"}}
        {{else}}
        ❌  Build #{{build.number}} of `{{repo.name}}` failed.
        📝 Commit by {{commit.author}} on `{{commit.branch}}`:
        ``` {{commit.message}} ```
        🌐 {{ build.link }}
        ✅ duration: {{duration build.started build.finished}}
        ✅ started: {{datetime build.started "2006/01/02 15:04" "UTC"}}
        ✅ finished: {{datetime build.finished "2006/01/02 15:04" "UTC"}}
        {{/success}}
    when:
      status:
      - success
      - failure

    volumes:
      - name: docker
        path: /var/lib/docker

  volumes:
    - name: cache
      host:
        path: /var/cache
    - name: docker
      host:
        path: /var/cache/${DRONE_REPO}/docker
