language: rust
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_script:
  - psql -c "create user rrr with password 'rrr' superuser;" -U postgres
  - psql -c 'create database rrr with owner rrr;' -U postgres
before_install:
  - cd server
script:
  - cargo test --all
env:
  - DATABASE_URL=postgres://rrr:rrr@localhost/rrr
addons:
  postgresql: "9.4"
