language: rust
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_cache:
  - cd server
cache: cargo
before_script:
  - psql -c "create user rrr with password 'rrr' superuser;" -U postgres
  - psql -c 'create database rrr with owner rrr;' -U postgres
before_install:
  - cd server
script:
  - cargo install diesel_cli --no-default-features --features postgres
  - cargo build
  - diesel migration run
  - cargo build --all
  - cargo test --all
env:
  global:
  - DATABASE_URL=postgres://rrr:rrr@localhost/rrr
  - PGPORT=5433
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
