language: rust
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
before_script:
  - psql -c "create user lemmy with password 'password' superuser;" -U postgres
  - psql -c 'create database lemmy with owner lemmy;' -U postgres
before_install:
  - cd server
script:
  - diesel migration run
  - cargo build
  - cargo test
env:
  - LEMMY_DATABASE_URL=postgres://lemmy:password@localhost:5432/lemmy
addons:
  postgresql: "9.4"
