language: rust
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
before_script:
  - psql -c "create user rrr with password 'rrr' superuser;" -U postgres
  - psql -c 'create database rrr with owner rrr;' -U postgres
before_install:
  - cd server
script:
  - cargo install --force diesel_cli --no-default-features --features postgres
  - diesel migration run
  - cargo build
  - cargo test
env:
  - DATABASE_URL=postgres://rrr:rrr@localhost/rrr
addons:
  postgresql: "9.4"
