version: '2.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rrr
      POSTGRES_PASSWORD: rrr
      POSTGRES_DB: rrr
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rrr"]
      interval: 5s
      timeout: 5s
      retries: 20
  lemmy:
    build: 
      context: .
    command: /bin/sh -c /app/lemmy
    ports:
      - "8536:8536"
    environment:
      LEMMY_FRONT_END_DIR: /app/dist
      DATABASE_URL: postgres://rrr:rrr@db:5432/rrr
      JWT_SECRET: changeme
      HOSTNAME: rrr
    restart: always
    depends_on: 
      db: 
        condition: service_healthy 
