apiVersion: skaffold/v1beta9
kind: Config
profiles:
  - name: lemmy--dev
    build:
      artifacts:
        - image: registry.gitlab.com/pojntfx/lemmy/server.dev
          context: server
          docker:
            dockerfile: Dockerfile.dev
        - image: registry.gitlab.com/pojntfx/lemmy/ui.dev
          context: ui
          docker:
            dockerfile: Dockerfile.dev
          sync:
            "***/*.ts": .
            "***/*.tsx": .
            "***/*.css": .
    deploy:
      kubectl:
        manifests:
          - "**/*.dev.yaml"
  - name: lemmy--prod
    build:
      artifacts:
        - image: registry.gitlab.com/pojntfx/lemmy/server.prod
          context: server
          docker:
            dockerfile: Dockerfile.prod
        - image: registry.gitlab.com/pojntfx/lemmy/ui.prod
          context: ui
          docker:
            dockerfile: Dockerfile.prod
    deploy:
      kubectl:
        manifests:
          - "**/*.prod.yaml"
