version: '3.3'

services:
  lemmy_db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=lemmy
    volumes:
      - lemmy_db:/var/lib/postgresql/data
  lemmy:
    image: dessalines/lemmy:v0.2.0.4
    ports:
      - "8536:8536"
    environment:
      - LEMMY_FRONT_END_DIR=/app/dist
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - HOSTNAME=${DOMAIN}
      - RATE_LIMIT_MESSAGE=${RATE_LIMIT_MESSAGE}
      - RATE_LIMIT_MESSAGE_PER_SECOND=${RATE_LIMIT_MESSAGE_PER_SECOND}
      - RATE_LIMIT_POST=${RATE_LIMIT_POST}
      - RATE_LIMIT_POST_PER_SECOND=${RATE_LIMIT_POST_PER_SECOND}
      - RATE_LIMIT_REGISTER=${RATE_LIMIT_REGISTER}
      - RATE_LIMIT_REGISTER_PER_SECOND=${RATE_LIMIT_REGISTER_PER_SECOND}
    restart: always
    depends_on:
      - lemmy_db
  lemmy_pictshare:
    image: hascheksolutions/pictshare:latest
    ports:
      - "8537:80"
    volumes:
      - lemmy_pictshare:/usr/share/nginx/html/data
volumes:
  lemmy_db:
  lemmy_pictshare:
