version: '3.3'

services:
  lemmy_alpha:
    image: lemmy-federation-test:latest
    ports:
      - "127.0.0.1:8540:8540"
    environment:
      - LEMMY_HOSTNAME=lemmy_alpha:8540
      - LEMMY_DATABASE_URL=postgres://lemmy:password@postgres_alpha:5432/lemmy
      - LEMMY_JWT_SECRET=changeme
      - LEMMY_FRONT_END_DIR=/app/dist
      - LEMMY_FEDERATION__ENABLED=true
      - LEMMY_FEDERATION__FOLLOWED_INSTANCES=lemmy_beta:8541
      - LEMMY_FEDERATION__TLS_ENABLED=false
      - LEMMY_PORT=8540
      - RUST_BACKTRACE=1
    restart: always
    depends_on:
      - postgres_alpha
  postgres_alpha:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres_alpha:/var/lib/postgresql/data
    restart: always

  lemmy_beta:
    image: lemmy-federation-test:latest
    ports:
      - "127.0.0.1:8541:8541"
    environment:
      - LEMMY_HOSTNAME=lemmy_beta:8541
      - LEMMY_DATABASE_URL=postgres://lemmy:password@postgres_beta:5432/lemmy
      - LEMMY_JWT_SECRET=changeme
      - LEMMY_FRONT_END_DIR=/app/dist
      - LEMMY_FEDERATION__ENABLED=true
      - LEMMY_FEDERATION__FOLLOWED_INSTANCES=lemmy_alpha:8540
      - LEMMY_FEDERATION__TLS_ENABLED=false
      - LEMMY_PORT=8541
      - RUST_BACKTRACE=1
    restart: always
    depends_on:
      - postgres_beta
  postgres_beta:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres_beta:/var/lib/postgresql/data
    restart: always

  iframely:
    image: dogbin/iframely:latest
    ports:
      - "127.0.0.1:8061:80"
    volumes:
      - ../iframely.config.local.js:/iframely/config.local.js:ro
    restart: always
