version: "3.3"

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - "9000:9000/tcp"
    volumes:
      - /opt/app/tools/volumes/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: lemmy-dev --interval 60