---
- hosts: all

  # Install python if required
  # https://www.josharcher.uk/code/ansible-python-connection-failure-ubuntu-server-1604/
  gather_facts: False
  pre_tasks:
    - name: install python for Ansible
      become: true
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-setuptools)
      args:
        executable: /bin/bash
      register: output
      changed_when: output.stdout != ""
    - setup: # gather facts

  tasks:
  - name: install dependencies
    become: true
    apt:
      pkg: ['nginx', 'docker-compose', 'docker.io', 'certbot', 'python-certbot-nginx']

  - name: request initial letsencrypt certificate
    become: true
    command: certbot certonly --nginx --agree-tos -d '{{ domain }}' -m '{{ letsencrypt_contact_email }}'
    args:
      creates: '/etc/letsencrypt/live/{{domain}}/privkey.pem'

  - name: create lemmy folder
    become: true
    file: path={{item.path}} state=directory
    with_items:
      - { path: '/lemmy/' }
      - { path: '/lemmy/volumes/' }

  - name:  add all template files
    become: true
    template: src={{item.src}} dest={{item.dest}}
    with_items:
      - { src: 'templates/env', dest: '/lemmy/.env' }
      - { src: '../docker/prod/docker-compose.yml', dest: '/lemmy/docker-compose.yml' }
      - { src: 'templates/nginx.conf', dest: '/etc/nginx/sites-enabled/lemmy.conf' }
    vars:
      postgres_password: "{{ lookup('password', 'passwords/{{ inventory_hostname }}/postgres chars=ascii_letters,digits') }}"
      jwt_password: "{{ lookup('password', 'passwords/{{ inventory_hostname }}/jwt chars=ascii_letters,digits') }}"

  - name: set env file permissions
    become: true
    file:
      path: "/lemmy/.env"
      state: touch
      mode: 0600
      access_time: preserve
      modification_time: preserve

  - name: enable and start docker service
    become: true
    systemd:
      name: docker
      enabled: yes
      state: started

  - name: start docker-compose
    become: true
    docker_compose:
      project_src: /lemmy/
      state: present
      pull: yes

  - name: reload nginx with new config
    become: true
    shell: nginx -s reload

  - name: certbot renewal cronjob
    become: true
    cron:
      special_time=daily
      name=certbot-renew-lemmy
      user=root
      job="certbot certonly --nginx -d '{{ domain }}' --deploy-hook 'docker-compose -f /peertube/docker-compose.yml exec nginx nginx -s reload'"
