version: '3.3'

services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "8540:8540"
      - "8550:8550"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - lemmy_alpha
      - pictshare_alpha
      - lemmy_beta
      - pictshare_beta
      - iframely
    restart: "always"

  lemmy_alpha:
    image: lemmy-federation:latest
    environment:
      - LEMMY_HOSTNAME=lemmy_alpha:8540
      - LEMMY_DATABASE_URL=postgres://lemmy:password@postgres_alpha:5432/lemmy
      - LEMMY_JWT_SECRET=changeme
      - LEMMY_FRONT_END_DIR=/app/dist
      - LEMMY_FEDERATION__ENABLED=true
      - LEMMY_FEDERATION__FOLLOWED_INSTANCES=lemmy_beta:8550
      - LEMMY_FEDERATION__TLS_ENABLED=false
      - LEMMY_PORT=8540
      - RUST_BACKTRACE=1
      - RUST_LOG=actix_web=debug
    restart: always
    depends_on:
      - postgres_alpha
  postgres_alpha:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres_alpha:/var/lib/postgresql/data
    restart: always
  pictshare_alpha:
    image: shtripok/pictshare:latest
    volumes:
      - ./volumes/pictshare_alpha:/usr/share/nginx/html/data
    restart: always

  lemmy_beta:
    image: lemmy-federation:latest
    environment:
      - LEMMY_HOSTNAME=lemmy_beta:8550
      - LEMMY_DATABASE_URL=postgres://lemmy:password@postgres_beta:5432/lemmy
      - LEMMY_JWT_SECRET=changeme
      - LEMMY_FRONT_END_DIR=/app/dist
      - LEMMY_FEDERATION__ENABLED=true
      - LEMMY_FEDERATION__FOLLOWED_INSTANCES=lemmy_alpha:8540
      - LEMMY_FEDERATION__TLS_ENABLED=false
      - LEMMY_PORT=8550
      - RUST_BACKTRACE=1
      - RUST_LOG=actix_web=debug
    restart: always
    depends_on:
      - postgres_beta
  postgres_beta:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres_beta:/var/lib/postgresql/data
    restart: always
  pictshare_beta:
    image: shtripok/pictshare:latest
    volumes:
      - ./volumes/pictshare_beta:/usr/share/nginx/html/data
    restart: always

  iframely:
    image: dogbin/iframely:latest
    volumes:
      - ../iframely.config.local.js:/iframely/config.local.js:ro
    restart: always
